pipeline {
  agent any

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            url: 'https://github.com/arjumand9794/anisble_project.git'
      }
    }

    stage('Terraform Init') {
      steps {
        dir('CI_pipeline/Terraform') {
          sh 'terraform init'
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        dir('CI_pipeline/Terraform') {
          sh 'terraform apply -auto-approve'
        }
      }
    }

    stage('Ansible Configure') {
      steps {
        sshagent(credentials: ['arj.pem']) {
          dir('CI_pipeline/Ansible') {
            sh 'ansible-playbook -i inventory site.yml'
          }
        }
      }
    }

  }
}


