pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION = 'us-east-1'
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main',
            url: 'https://github.com/arjumand9794/anisble_project.git'
      }
    }

    stage('Terraform Init') {
      steps {
        withCredentials([
          string(credentialsId: 'access_key', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'secrete_key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {
          dir('CI_pipeline/Terraform') {
            sh 'terraform init'
          }
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        withCredentials([
          string(credentialsId: 'access_key', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'secrete_key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {
          dir('CI_pipeline/Terraform') {
            sh 'terraform apply -auto-approve'
          }
        }
      }
    }

    stage('Ansible Configure') {
      steps {
        withCredentials([
          sshUserPrivateKey(
            credentialsId: 'ec2-user',
            keyFileVariable: 'SSH_KEY',
            usernameVariable: 'SSH_USER'
          )
        ]) {
          dir('CI_pipeline/Ansible') {
            sh '''
              chmod 600 $SSH_KEY
              ansible-playbook -i inventory site.yml \
                --user $SSH_USER \
                --private-key $SSH_KEY
            '''
          }
        }
      }
    }

  }
}





